cmon

diff --git a/.github/workflows/new-comment.yaml b/.github/workflows/new-comment.yaml
--- a/.github/workflows/new-comment.yaml
+++ b/.github/workflows/new-comment.yaml
@@ -26,7 +26,7 @@ jobs:
       - name: Is QA Approved?
         run: |
           echo "Is this PR Labeled? ${IS_LABELED}"
-          IS_LABELED === true && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
+          ${IS_LABELED} === true && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
         shell: bash
         env:
           IS_LABELED: ${{ steps.comment-labeler.outputs.labeled }}
