removed unneeded steps

diff --git a/.github/workflows/new-comment.yaml b/.github/workflows/new-comment.yaml
--- a/.github/workflows/new-comment.yaml
+++ b/.github/workflows/new-comment.yaml
@@ -18,18 +18,18 @@ jobs:
           keywords: '["[QA Approved]"]'
           labels: '["qa-approved"]'
           github-token: "${{ secrets.GITHUB_TOKEN }}"
-      - name: Comment Labeler Output
-        run: echo "view your env"
-        shell: bash
-        env:
-          OUTPUT: ${{ toJSON(steps.comment-labeler) }}
-      - name: Is QA Approved?
-        run: |
-          echo "Is this PR Labeled? ${IS_LABELED}"
-          ${IS_LABELED} === true && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
-        shell: bash
-        env:
-          IS_LABELED: ${{ steps.comment-labeler.outputs.labeled }}
+      # - name: Comment Labeler Output
+      #   run: echo "view your env"
+      #   shell: bash
+      #   env:
+      #     OUTPUT: ${{ toJSON(steps.comment-labeler) }}
+      # - name: Is QA Approved?
+      #   run: |
+      #     echo "Is this PR Labeled? ${IS_LABELED}"
+      #     ${IS_LABELED} === true && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
+      #   shell: bash
+      #   env:
+      #     IS_LABELED: ${{ steps.comment-labeler.outputs.labeled }}
   check-label:
     name: Is QA Approved
     runs-on: ubuntu-latest
@@ -38,7 +38,7 @@ jobs:
       - run: |
           echo "Is this PR Labeled? ${IS_LABELED}"
           echo "needs ${IS_LABELED}"
-        #          IS_LABELED === "true" && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
+          ${IS_LABELED} === true && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
         shell: bash
         env:
           ERROR_MESSAGE: "QA Approved label not found"
