restructure

diff --git a/.github/workflows/new-comment.yaml b/.github/workflows/new-comment.yaml
--- a/.github/workflows/new-comment.yaml
+++ b/.github/workflows/new-comment.yaml
@@ -1,4 +1,4 @@
-name: "Handle new comments"
+name: "QA Approval"
 on:
   issue_comment:
     types: [created]
@@ -19,17 +19,18 @@ jobs:
           labels: '["qa-approved"]'
           github-token: "${{ secrets.GITHUB_TOKEN }}"
   check-label:
-    name: Is QA Approved
+    name: QA Approval
     runs-on: ubuntu-latest
     needs: pull-request-comment
     steps:
       - run: |
-          echo "Is this PR Labeled? ${IS_LABELED}"
-          echo "contains? ${{ contains(env.GITHUB_CONTEXT, 'qa-approved' ) }}"
-          ${IS_LABELED} || ${{ contains(env.GITHUB_CONTEXT, 'qa-approved' ) }} && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
+          ERROR_MESSAGE="QA Approved label not found"
+          echo "Was this PR just labeled by this workflow? ${IS_LABELED}"
+          echo "Already labeled qa-approved? ${ HAS_QA_LABEL ) }"
+          ${IS_LABELED} || ${HAS_QA_LABEL} && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
         shell: bash
         env:
-          ERROR_MESSAGE: "QA Approved label not found"
           IS_LABELED: ${{needs.pull-request-comment.outputs.labeled}}
-          GITHUB_CONTEXT: ${{ toJSON(github.event.issue.labels.*.name) }}
+          GITHUB_LABELS: ${{ toJSON(github.event.issue.labels.*.name) }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          HAS_QA_LABEL: ${{ contains(toJSON(github.event.issue.labels.*.name), 'qa-approved') }}
